// .agents/ -> .claude/ + .mcp.json
const GEN = "generated by scripts/sync-agents.mjs; edit .agents/ instead";
const hook = (file) => ({
  type: "command",
  command: `node "$CLAUDE_PROJECT_DIR/.agents/hooks/${file}"`,
});

export default {
  name: "claude",
  roots: [".claude/agents", ".claude/skills"],
  generate({ agents, skills, mcp }) {
    const out = {};
    for (const a of agents) {
      const tools = a.readonly ? a.tools : a.tools;
      out[`.claude/agents/${a.name}.md`] =
        `---\nname: ${a.name}\ndescription: "${a.description.replace(/"/g, '\\"')}"\ntools: ${tools}\n---\n<!-- ${GEN} -->\n${a.body}`;
    }
    for (const s of skills) {
      out[`.claude/skills/${s.name}/SKILL.md`] =
        `---\nname: ${s.name}\ndescription: "${s.description.replace(/"/g, '\\"')}"\n---\n<!-- ${GEN} -->\n${s.body}`;
    }
    out[".claude/settings.json"] =
      JSON.stringify(
        {
          $schema: "https://json.schemastore.org/claude-code-settings.json",
          hooks: {
            PreToolUse: [
              { matcher: "Edit|Write|MultiEdit", hooks: [hook("enforce-owner.mjs")] },
              { matcher: "Bash", hooks: [hook("guard-git-staging.mjs")] },
            ],
            PostToolUse: [{ matcher: "Edit|Write|MultiEdit", hooks: [hook("format-on-edit.mjs")] }],
          },
        },
        null,
        2,
      ) + "\n";
    out[".mcp.json"] = JSON.stringify({ mcpServers: mcp }, null, 2) + "\n";
    return out;
  },
  keep: [".claude/settings.local.json"],
};
