// .agents/ -> .codex/ (Codex reads .agents/skills and root AGENTS.md directly)
const GEN = "generated by scripts/sync-agents.mjs; edit .agents/ instead";
const hook = (file) => ({
  type: "command",
  command: `node "$(git rev-parse --show-toplevel)/.agents/hooks/${file}"`,
});

export default {
  name: "codex",
  roots: [".codex"],
  generate({ agents, mcp }) {
    const out = {};
    for (const a of agents) {
      out[`.codex/agents/${a.name}.toml`] =
        `# ${GEN}\nname = "${a.name}"\ndescription = ${JSON.stringify(a.description)}\n` +
        (a.readonly ? 'sandbox_mode = "read-only"\n' : "") +
        `developer_instructions = '''\n${a.body.trim()}\n'''\n`;
    }
    out[".codex/hooks.json"] =
      JSON.stringify(
        {
          hooks: {
            PreToolUse: [
              { matcher: "apply_patch|Edit|Write", hooks: [hook("enforce-owner.mjs")] },
              { matcher: "Bash", hooks: [hook("guard-git-staging.mjs")] },
            ],
            PostToolUse: [{ matcher: "apply_patch|Edit|Write", hooks: [hook("format-on-edit.mjs")] }],
          },
        },
        null,
        2,
      ) + "\n";
    out[".codex/config.toml"] =
      `# ${GEN}\n` +
      Object.entries(mcp)
        .map(
          ([n, s]) =>
            `[mcp_servers.${n}]\ncommand = ${JSON.stringify(s.command)}\nargs = ${JSON.stringify(s.args)}\n`,
        )
        .join("\n");
    return out;
  },
};
