import {
  bestFreeSlot,
  slotPreferenceScore,
  stabilityScore,
} from "../core/slot-score";
import { findConflictingTaskIds } from "../core/sync-conflicts";
import { PREFERENCE_MATRIX_LENGTH } from "@zenflow/shared";

/**
 * Golden fixtures for the scheduler core's frozen fallback (ADR-0003 phase
 * 6): a deterministic set of `{ input, output }` cases per pure function that
 * survives as the frozen TS fallback (`slot-score.ts`, `sync-conflicts.ts`),
 * produced by the TypeScript implementation and consumed by the Python
 * port's test-suite (`services/bandit`) so the frozen fallback and its
 * Python-side parity check cannot silently drift. All LinUCB / displacement /
 * arm-scoring math moved to `services/bandit/src/core` and is no longer
 * golden-tested here (Python's own tests are authoritative for it).
 *
 * Everything here is fully deterministic — fixed instants, fixed matrices, no
 * clock, no randomness. Regenerate with
 * `pnpm --filter backend golden:export`; `golden-fixtures.spec.ts` fails when
 * the committed JSON no longer matches the code (drift).
 *
 * Wire conventions: instants are epoch milliseconds; `Interval`s are
 * `{ start, end }`; absent results are `null`.
 */

export const GOLDEN_FIXTURES_VERSION = 1;

const ms = (iso: string) => Date.parse(iso);

/** A deterministic, non-trivial 7x24 preference matrix (values in [-1, 1]). */
export function goldenPreferenceMatrix(): number[] {
  return Array.from({ length: PREFERENCE_MATRIX_LENGTH }, (_, i) => {
    const hour = i % 24;
    const wd = Math.floor(i / 24);
    const base =
      hour >= 8 && hour < 12 ? 0.8 : hour >= 20 || hour < 6 ? -0.6 : 0.1;
    return Math.round((base - wd * 0.03) * 1000) / 1000;
  });
}

/** Builds the full, deterministic golden fixture document. */
export function buildGoldenFixtures() {
  const pref = goldenPreferenceMatrix();
  const rangeMs = {
    startMs: ms("2026-06-15T08:00:00.000Z"),
    endMs: ms("2026-06-15T10:00:00.000Z"),
  };

  return {
    version: GOLDEN_FIXTURES_VERSION,
    note: "Generated by backend/scripts/export-golden-fixtures.ts - do not edit by hand.",
    slotPreferenceScore: [
      { s: "2026-06-15T09:00:00.000Z", e: "2026-06-15T10:00:00.000Z" },
      { s: "2026-06-15T09:15:00.000Z", e: "2026-06-15T11:00:00.000Z" },
      { s: "2026-06-15T23:00:00.000Z", e: "2026-06-16T01:00:00.000Z" },
    ].map((c) => ({
      input: {
        prefMatrix: pref,
        startMs: ms(c.s),
        endMs: ms(c.e),
        timezone: "UTC",
      },
      output: slotPreferenceScore(pref, ms(c.s), ms(c.e), "UTC"),
    })),
    stabilityScore: [0, 15, 60, 240, 100000].map((mins) => ({
      input: {
        prevStartMs: ms("2026-06-15T09:00:00.000Z"),
        newStartMs: ms("2026-06-15T09:00:00.000Z") + mins * 60_000,
      },
      output: stabilityScore(
        ms("2026-06-15T09:00:00.000Z"),
        ms("2026-06-15T09:00:00.000Z") + mins * 60_000,
      ),
    })),
    bestFreeSlot: [
      { name: "highest preference wins", occupied: [], deadline: null },
      {
        name: "avoids an occupied interval",
        occupied: [
          {
            start: ms("2026-06-15T08:00:00.000Z"),
            end: ms("2026-06-15T12:00:00.000Z"),
          },
        ],
        deadline: null,
      },
      {
        name: "non-aligned deadline",
        occupied: [],
        deadline: ms("2026-06-15T10:10:00.000Z"),
      },
    ].map((c) => {
      const windowStart = rangeMs.startMs - 4 * 3_600_000;
      const windowEnd = c.deadline ?? ms("2026-06-16T00:00:00.000Z");
      const out = bestFreeSlot(
        60,
        c.occupied,
        new Date(windowStart),
        new Date(windowEnd),
        pref,
        "UTC",
        new Date(windowEnd),
      );
      return {
        name: c.name,
        input: {
          durationMinutes: 60,
          occupied: c.occupied,
          windowStartMs: windowStart,
          windowEndMs: windowEnd,
          fitWindowEndMs: windowEnd,
          prefMatrix: pref,
          timezone: "UTC",
        },
        output: out ? out.getTime() : null,
      };
    }),
    findConflictingTaskIds: [
      {
        fixed: [{ start: 1_000 * 60_000, end: 1_060 * 60_000 }],
        tasks: [
          { id: "b", startMs: 1_030 * 60_000, durationMinutes: 30 },
          { id: "a", startMs: 970 * 60_000, durationMinutes: 30 },
          { id: "c", startMs: 1_000 * 60_000, durationMinutes: 15 },
        ],
      },
    ].map((input) => ({
      input,
      output: findConflictingTaskIds(input.fixed, input.tasks),
    })),
  };
}
