name: zenflow-prod
services:
  api:
    container_name: zenflow-api-staging
    image: zenflow-api:2.1.0
    expose:
      - "5000"
    networks:
      - api
    volumes:
      - uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      redis-ratelimit:
        condition: service_started
      mail:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env.staging

  migrations:
    container_name: zenflow-db-migration-staging
    image: zenflow-api:2.1.0
    networks:
      - api
    command: pnpm prisma:migrate:deploy
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.staging

  postgres:
    container_name: zenflow-db-staging
    image: postgres:18.4-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - docker.staging.env
    networks:
      - api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: zenflow-cache-staging
    image: redis:8.8.0-alpine
    expose:
      - "6379"
    networks:
      - api

  redis-ratelimit:
    container_name: zenflow-cache-ratelimit-staging
    image: redis:8.8.0-alpine
    expose:
      - "6379"
    networks:
      - api

  mail:
    container_name: zenflow-mail-staging
    image: mailhog/mailhog:v1.0.1
    expose:
      - "1025"
    ports:
      - 8025:8025
    networks:
      - api

  caddy:
    image: caddy:2.11.4
    container_name: caddy-staging
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile.staging:/etc/caddy/Caddyfile
    depends_on:
      - api
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  uploads:
