name: zenflow-dev
services:
  postgres:
    container_name: zenflow-db
    image: postgres:18.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.dev.env
    networks:
      - db

  redis:
    container_name: zenflow-cache
    image: redis:8.8.0-alpine
    ports:
      - 6379:6379
    networks:
      - cache

  mail:
    container_name: zenflow-mail
    image: mailhog/mailhog:v1.0.1
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mail

networks:
  db:
    driver: bridge
  cache:
    driver: bridge
  mail:
    driver: bridge
