"""Mirror of the scheduler constants in ``backend/src/scheduler/constants.ts``."""

TIME_GRANULARITY = 15
MS_PER_MINUTE = 60_000
SLOT_MS = TIME_GRANULARITY * MS_PER_MINUTE
HOUR_MS = 60 * MS_PER_MINUTE
DAY_MS = 24 * 60 * MS_PER_MINUTE

MAX_SCAN_DAYS = 60
PREFERENCE_LEARNING_RATE = 0.1
PREFERENCE_RETAINED_WEIGHT = 0.25
STABILITY_WEIGHT = 0.1
STABILITY_SATURATION_HOURS = 4
MOVE_REWARD_SCALE_MINUTES = 240
MATRIX_HALF_LIFE_DAYS = 21

PREFERENCE_SLOTS_PER_DAY = 24
PREFERENCE_MATRIX_LENGTH = 7 * PREFERENCE_SLOTS_PER_DAY
FEATURE_DIM = 22

DURATION_DIVISOR = 480
WORKLOAD_HOURS_DIVISOR = 12
WORKLOAD_COUNT_DIVISOR = 8
WORKLOAD_TYPES = ("LECTURE", "ASSIGNMENT", "EXAM", "TASK", "DND")
