import {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  ArrowUp,
  Baby,
  BadgeAlert,
  BarChart3,
  Bell,
  Bold,
  BookOpen,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Fan,
  GalleryHorizontal,
  Github,
  Globe,
  GraduationCap,
  Highlighter,
  Home,
  Info,
  Italic,
  Lamp,
  Lightbulb,
  LayoutGrid,
  LayoutPanelLeft,
  LifeBuoy,
  Link2,
  List,
  ListOrdered,
  Loader,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  MenuSquare,
  MessageCircleQuestion,
  MessageSquare,
  MinusCircle,
  Moon,
  MoonStar,
  MousePointer2,
  Notebook,
  Palette,
  Plus,
  PlusCircle,
  Quote,
  RefreshCcw,
  RefreshCw,
  RotateCw,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  Sliders,
  Smartphone,
  Sparkles,
  Star,
  Sun,
  Table,
  Tag,
  Terminal,
  Trash2,
  Underline,
  Upload,
  User,
  UserPlus,
  Users,
  X,
} from "lucide-react-native";
import { cssInterop } from "nativewind";
function interopIcon(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: "style",
      nativeStyleToProp: {
        color: true,
        opacity: true,
      },
    },
  });
}
interopIcon(Settings);
interopIcon(Sun);
interopIcon(MoonStar);
interopIcon(AlignJustify);
interopIcon(Activity);
interopIcon(Airplay);
interopIcon(AlarmClockIcon);
interopIcon(AlertCircle);
interopIcon(AlignRight);
interopIcon(Baby);
interopIcon(Loader);
interopIcon(BadgeAlert);
interopIcon(Calendar);
interopIcon(CircleUserRound);
interopIcon(Database);
interopIcon(Ear);
interopIcon(Fan);
interopIcon(GalleryHorizontal);
interopIcon(Lamp);
interopIcon(Lightbulb);
interopIcon(Table);
interopIcon(ArrowDown);
interopIcon(ArrowUp);
interopIcon(ChevronDown);
interopIcon(LayoutPanelLeft);
interopIcon(MenuSquare);
interopIcon(Check);
interopIcon(CheckCircle);
interopIcon(ChevronsDownUp);
interopIcon(ChevronsUpDown);
interopIcon(Copy);
interopIcon(CalendarDays);
interopIcon(Sparkles);
interopIcon(Bold);
interopIcon(Italic);
interopIcon(Underline);
interopIcon(AlignLeft);
interopIcon(Info);
interopIcon(X);
interopIcon(Search);
interopIcon(ChevronRight);
interopIcon(ChevronLeft);
interopIcon(ChevronUp);
interopIcon(Cloud);
interopIcon(LifeBuoy);
interopIcon(LogOut);
interopIcon(Mail);
interopIcon(MessageSquare);
interopIcon(Plus);
interopIcon(PlusCircle);
interopIcon(UserPlus);
interopIcon(Users);
interopIcon(AlignCenter);
interopIcon(Terminal);
interopIcon(AlertTriangle);
interopIcon(Code);
interopIcon(CheckSquare);
interopIcon(Github);
interopIcon(Home);
interopIcon(Shield);
interopIcon(Star);
interopIcon(Bell);
interopIcon(Archive);
interopIcon(BookOpen);
interopIcon(Moon);
interopIcon(Palette);
interopIcon(Smartphone);
interopIcon(Clock);
interopIcon(MessageCircleQuestion);
interopIcon(MinusCircle);
interopIcon(MousePointer2);
interopIcon(CalendarRange);
interopIcon(LayoutGrid);
interopIcon(BarChart3);
interopIcon(Sliders);
interopIcon(User);
interopIcon(Globe);
interopIcon(Lock);
interopIcon(Tag);
interopIcon(Highlighter);
interopIcon(Link2);
interopIcon(List);
interopIcon(ListOrdered);
interopIcon(Quote);
interopIcon(RefreshCcw);
interopIcon(RefreshCw);
interopIcon(RotateCw);
interopIcon(Upload);
interopIcon(Trash2);
interopIcon(RefreshCcw);
interopIcon(Scale);
interopIcon(CalendarClock);
interopIcon(ClipboardList);
interopIcon(GraduationCap);
interopIcon(Notebook);

export {
  Activity,
  Airplay,
  AlarmClockIcon,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowUp,
  Baby,
  BadgeAlert,
  BarChart3,
  Bold,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle,
  LayoutGrid,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDownUp,
  ChevronsUpDown,
  CircleUserRound,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Copy,
  Database,
  Ear,
  Fan,
  GalleryHorizontal,
  Globe,
  GraduationCap,
  Highlighter,
  Info,
  Italic,
  Lamp,
  Lightbulb,
  LayoutPanelLeft,
  LifeBuoy,
  Link2,
  List,
  ListOrdered,
  Lock,
  Loader,
  LogOut,
  Settings,
  Mail,
  MenuSquare,
  MessageCircleQuestion,
  MessageSquare,
  MinusCircle,
  MoonStar,
  MousePointer2,
  Notebook,
  Plus,
  PlusCircle,
  Quote,
  RefreshCcw,
  RefreshCw,
  RotateCw,
  Scale,
  Search,
  Sparkles,
  Sun,
  Table,
  Tag,
  Terminal,
  Trash2,
  Underline,
  Upload,
  UserPlus,
  Home,
  Users,
  X,
  Send,
  type LucideIcon,
  Archive,
  Bell,
  BookOpen,
  Shield,
  Sliders,
  Star,
  User,
  Moon,
  Palette,
  Smartphone,
};
