/** Translate messages generated by the shared schema without changing its contract. */
export function localizeValidation(
  key: string,
  language: "en" | "vi",
): string | undefined {
  if (language !== "vi") return undefined;
  const patterns: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
    [
      /^Could not sign in to your DLU (.+) account\. Check your username and password\.$/,
      (match) =>
        `Không thể đăng nhập tài khoản DLU ${match[1]}. Kiểm tra tài khoản và mật khẩu.`,
    ],
    [
      /^No (.+) account connected$/,
      (match) => `Chưa kết nối tài khoản ${match[1]}.`,
    ],
    [
      /^Can't reduce to (\d+) sessions — one of the sessions being removed has already started\.$/,
      (match) =>
        `Không thể giảm còn ${match[1]} buổi vì một buổi cần xóa đã bắt đầu.`,
    ],
    [
      /^Cannot find (?:session|TASK series|recurring series|series with id)(?: with id)? .+$/,
      () => "Không tìm thấy lịch này. Có thể lịch đã bị xóa.",
    ],
    [
      /^Invalid occurrence start .+$/,
      () => "Thời gian bắt đầu của lần lặp không hợp lệ.",
    ],
    [
      /^Cannot find (?:conflict )?notification(?: with id)? .+$/,
      () => "Không tìm thấy thông báo này.",
    ],
    [
      /^Day number must be between 0 and 6, got (.+)$/,
      (match) => `Số thứ trong tuần phải từ 0 đến 6, đã nhận ${match[1]}.`,
    ],
    [/^(.+) must be an email$/, () => "Vui lòng nhập địa chỉ email hợp lệ."],
    [/^(.+) should not be empty$/, () => "Vui lòng điền thông tin bắt buộc."],
    [/^(.+) must be an integer number$/, () => "Vui lòng nhập số nguyên."],
    [
      /^(.+) must be longer than or equal to (\d+) characters$/,
      (match) => `Thông tin phải có ít nhất ${match[2]} ký tự.`,
    ],
    [
      /^(.+) must be shorter than or equal to (\d+) characters$/,
      (match) => `Thông tin không được vượt quá ${match[2]} ký tự.`,
    ],
    [
      /^Not enough time for (\d+) sessions before this deadline\nChoose a later deadline or fewer sessions\.$/,
      (match) =>
        `Không đủ thời gian cho ${match[1]} buổi trước hạn chót\nChọn hạn chót muộn hơn hoặc giảm số buổi.`,
    ],
    [
      /^Title must be at most (\d+) characters\.$/,
      (match) => `Tiêu đề không được vượt quá ${match[1]} ký tự.`,
    ],
    [
      /^Session duration must be at least (\d+) minutes$/,
      (match) => `Thời lượng tối thiểu là ${match[1]} phút`,
    ],
    [
      /^Duration must be a multiple of (\d+) minutes$/,
      (match) => `Thời lượng phải là bội số của ${match[1]} phút`,
    ],
    // Zod's generated messages cover integer reminders and their array limit.
    [
      /^Too big: expected array to have <=([\d]+) items$/,
      (match) => `Tối đa ${match[1]} mục.`,
    ],
    [
      /^Too small: expected number to be >=([\d]+)$/,
      (match) => `Giá trị phải từ ${match[1]} trở lên.`,
    ],
    [
      /^Too big: expected number to be <=([\d]+)$/,
      (match) => `Giá trị không được vượt quá ${match[1]}.`,
    ],
    [
      /^Invalid input: expected int, received number$/,
      () => "Vui lòng nhập số nguyên.",
    ],
    [
      /^Invalid input: expected number, received (?:NaN|undefined|string|null)$/,
      () => "Vui lòng nhập số hợp lệ.",
    ],
    [
      /^Invalid input: expected string, received (?:undefined|null|number)$/,
      () => "Vui lòng nhập văn bản hợp lệ.",
    ],
    [
      /^Invalid option: expected one of .+$/,
      () => "Vui lòng chọn một loại lịch hợp lệ.",
    ],
  ];
  for (const [pattern, translate] of patterns) {
    const match = key.match(pattern);
    if (match) return translate(match);
  }
  return undefined;
}
